# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client-ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# from curses import window
import subprocess
import sys
from unicodedata import name
import images_rc
import icons_rc
from base64 import encode
import socket
import traceback
import os
from handle_json import *
from PyQt5 import QtCore, QtGui, QtWidgets

HOST = "127.0.0.1"
SERVER_PORT = 65432
FORMAT = "utf8"
SEPARATOR = "</>"
BUFFER_SIZE = 1024
END_MESSAGE_SIZE = 17
SMALL_PIC_FOLDER = "data/avatar/small"
BIG_PIC_FOLDER = "data/avatar/big"


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1200, 800)
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:rgb(255, 255, 255); \n"
                                         "font: 8pt \"Calibri\";")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_container = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.left_container.sizePolicy().hasHeightForWidth())
        self.left_container.setSizePolicy(sizePolicy)
        self.left_container.setMinimumSize(QtCore.QSize(0, 0))
        self.left_container.setMaximumSize(QtCore.QSize(800, 16777215))
        self.left_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_container.setObjectName("left_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_container)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_bar_container = QtWidgets.QFrame(self.left_container)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.search_bar_container.sizePolicy().hasHeightForWidth())
        self.search_bar_container.setSizePolicy(sizePolicy)
        self.search_bar_container.setMinimumSize(QtCore.QSize(0, 80))
        self.search_bar_container.setMaximumSize(
            QtCore.QSize(16777215, 16777215))
        self.search_bar_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_bar_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_bar_container.setObjectName("search_bar_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(
            self.search_bar_container)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search_input_field = QtWidgets.QLineEdit(
            self.search_bar_container)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.search_input_field.sizePolicy().hasHeightForWidth())
        self.search_input_field.setSizePolicy(sizePolicy)
        self.search_input_field.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.search_input_field.setStyleSheet(
            "font: 14pt \"Calibri\"; background-color:rgb(85, 255, 255); border-radius: 20px")
        self.search_input_field.setText("")
        self.search_input_field.setAlignment(QtCore.Qt.AlignCenter)
        self.search_input_field.setClearButtonEnabled(True)
        self.search_input_field.setObjectName("search_input_field")
        self.horizontalLayout_2.addWidget(self.search_input_field)
        self.search_button = QtWidgets.QPushButton(self.search_bar_container)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.search_button.sizePolicy().hasHeightForWidth())
        self.search_button.setSizePolicy(sizePolicy)
        self.search_button.setMinimumSize(QtCore.QSize(56, 0))
        self.search_button.setStyleSheet(
            "border-radius:20px; background-color:rgb(255, 250, 171)")
        self.search_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/search.svg"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon)
        self.search_button.setCheckable(True)
        self.search_button.setChecked(True)
        self.search_button.setAutoDefault(False)
        self.search_button.setDefault(False)
        self.search_button.setFlat(False)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_2.addWidget(self.search_button)
        self.verticalLayout.addWidget(self.search_bar_container)
        self.search_result_container = QtWidgets.QFrame(self.left_container)
        self.search_result_container.setFrameShape(
            QtWidgets.QFrame.StyledPanel)
        self.search_result_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_result_container.setObjectName("search_result_container")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(
            self.search_result_container)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.profile_pic_container = QtWidgets.QWidget(
            self.search_result_container)
        self.profile_pic_container.setMinimumSize(QtCore.QSize(0, 0))
        self.profile_pic_container.setMaximumSize(QtCore.QSize(500, 16777215))
        self.profile_pic_container.setStyleSheet(
            "background-color: rgb(157, 255, 210); border-radius:10px")
        self.profile_pic_container.setObjectName("profile_pic_container")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(
            self.profile_pic_container)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.profile_pic_label = QtWidgets.QLabel(self.profile_pic_container)
        self.profile_pic_label.setStyleSheet("font: 18pt \"Calibri\";")
        self.profile_pic_label.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_pic_label.setObjectName("profile_pic_label")
        self.verticalLayout_3.addWidget(self.profile_pic_label)
        self.frame_10 = QtWidgets.QFrame(self.profile_pic_container)
        self.frame_10.setStyleSheet("border-radius:200px")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.big_pic_container = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.big_pic_container.sizePolicy().hasHeightForWidth())
        self.big_pic_container.setSizePolicy(sizePolicy)
        self.big_pic_container.setMaximumSize(QtCore.QSize(16777215, 478))
        self.big_pic_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.big_pic_container.setText("")
        self.big_pic_container.setPixmap(
            QtGui.QPixmap(":/images/images/default-pic.png"))
        self.big_pic_container.setScaledContents(True)
        self.big_pic_container.setObjectName("big_pic_container")
        self.verticalLayout_5.addWidget(self.big_pic_container)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_8 = QtWidgets.QFrame(self.profile_pic_container)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3.addWidget(self.frame_8)
        self.horizontalLayout_3.addWidget(self.profile_pic_container)
        self.info_container = QtWidgets.QWidget(self.search_result_container)
        self.info_container.setStyleSheet("border-radius: 10px; \n"
                                          "font: 14pt \"Calibri\";\n"
                                          "background-color: rgb(255, 196, 255);")
        self.info_container.setObjectName("info_container")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.info_container)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.info_label = QtWidgets.QLabel(self.info_container)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.info_label.setFont(font)
        self.info_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_label.setStyleSheet("font: 18pt \"Calibri\";")
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setWordWrap(False)
        self.info_label.setObjectName("info_label")
        self.verticalLayout_4.addWidget(self.info_label)
        self.frame_4 = QtWidgets.QFrame(self.info_container)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.id_icon = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.id_icon.sizePolicy().hasHeightForWidth())
        self.id_icon.setSizePolicy(sizePolicy)
        self.id_icon.setStyleSheet("background-color: rgb(239, 159, 239)")
        self.id_icon.setText("")
        self.id_icon.setPixmap(QtGui.QPixmap(":/icons/icons/face-id.svg"))
        self.id_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.id_icon.setObjectName("id_icon")
        self.horizontalLayout_6.addWidget(self.id_icon)
        self.id_container = QtWidgets.QLabel(self.frame_4)
        self.id_container.setIndent(8)
        self.id_container.setObjectName("id_container")
        self.horizontalLayout_6.addWidget(self.id_container)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_7 = QtWidgets.QFrame(self.info_container)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.name_icon = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.name_icon.sizePolicy().hasHeightForWidth())
        self.name_icon.setSizePolicy(sizePolicy)
        self.name_icon.setStyleSheet("background-color: rgb(239, 159, 239)")
        self.name_icon.setText("")
        self.name_icon.setPixmap(QtGui.QPixmap(":/icons/icons/id.svg"))
        self.name_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.name_icon.setObjectName("name_icon")
        self.horizontalLayout_7.addWidget(self.name_icon)
        self.name_container = QtWidgets.QLabel(self.frame_7)
        self.name_container.setIndent(8)
        self.name_container.setObjectName("name_container")
        self.horizontalLayout_7.addWidget(self.name_container)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.info_container)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.phone_icon = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.phone_icon.sizePolicy().hasHeightForWidth())
        self.phone_icon.setSizePolicy(sizePolicy)
        self.phone_icon.setStyleSheet("background-color: rgb(239, 159, 239)")
        self.phone_icon.setText("")
        self.phone_icon.setPixmap(QtGui.QPixmap(":/icons/icons/phone.svg"))
        self.phone_icon.setScaledContents(False)
        self.phone_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.phone_icon.setObjectName("phone_icon")
        self.horizontalLayout_8.addWidget(self.phone_icon)
        self.phone_container = QtWidgets.QLabel(self.frame_6)
        self.phone_container.setIndent(8)
        self.phone_container.setObjectName("phone_container")
        self.horizontalLayout_8.addWidget(self.phone_container)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.info_container)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.email_icon = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.email_icon.sizePolicy().hasHeightForWidth())
        self.email_icon.setSizePolicy(sizePolicy)
        self.email_icon.setStyleSheet("background-color: rgb(239, 159, 239)")
        self.email_icon.setText("")
        self.email_icon.setPixmap(QtGui.QPixmap(":/icons/icons/mail.svg"))
        self.email_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.email_icon.setObjectName("email_icon")
        self.horizontalLayout_9.addWidget(self.email_icon)
        self.email_container = QtWidgets.QLabel(self.frame_5)
        self.email_container.setIndent(8)
        self.email_container.setObjectName("email_container")
        self.horizontalLayout_9.addWidget(self.email_container)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.horizontalLayout_3.addWidget(self.info_container)
        self.verticalLayout.addWidget(self.search_result_container)
        self.horizontalLayout.addWidget(self.left_container)
        self.right_container = QtWidgets.QFrame(self.centralwidget)
        self.right_container.setMinimumSize(QtCore.QSize(300, 0))
        self.right_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_container.setObjectName("right_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.right_container)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(5, 0))
        self.frame_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.contact_icon = QtWidgets.QLabel(self.frame)
        self.contact_icon.setStyleSheet("font: 14pt \"Calibri\";")
        self.contact_icon.setText("")
        self.contact_icon.setPixmap(
            QtGui.QPixmap(":/icons/icons/address-book.svg"))
        self.contact_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.contact_icon.setObjectName("contact_icon")
        self.horizontalLayout_5.addWidget(self.contact_icon)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(5, 0))
        self.frame_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.frame)
        self.list_container = QtWidgets.QFrame(self.right_container)
        self.list_container.setStyleSheet("background-color: rgb(255, 170, 127); \n"
                                          "border-radius:10px;\n"
                                          "")
        self.list_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.list_container.setObjectName("list_container")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.list_container)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_13 = QtWidgets.QFrame(self.list_container)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_20 = QtWidgets.QFrame(self.frame_13)
        self.frame_20.setStyleSheet(
            "border-right: 4px solid red; border-radius: 0px")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.name1 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name1.setFont(font)
        self.name1.setStyleSheet("font: bold 12pt \"Calibri\";\n"
                                 "border-right:0px")
        self.name1.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.name1.setIndent(10)
        self.name1.setObjectName("name1")
        self.verticalLayout_7.addWidget(self.name1)
        self.id1 = QtWidgets.QLabel(self.frame_20)
        self.id1.setStyleSheet("font: 10pt \"Calibri\";\n"
                               "border-right: 0px")
        self.id1.setAlignment(QtCore.Qt.AlignRight |
                              QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.id1.setIndent(10)
        self.id1.setObjectName("id1")
        self.verticalLayout_7.addWidget(self.id1)
        self.horizontalLayout_10.addWidget(self.frame_20)
        self.small_pic1 = QtWidgets.QLabel(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.small_pic1.sizePolicy().hasHeightForWidth())
        self.small_pic1.setSizePolicy(sizePolicy)
        self.small_pic1.setMinimumSize(QtCore.QSize(85, 85))
        self.small_pic1.setMaximumSize(QtCore.QSize(85, 85))
        self.small_pic1.setStyleSheet("")
        self.small_pic1.setText("")
        self.small_pic1.setPixmap(QtGui.QPixmap(
            ":/images/images/default-pic.png"))
        self.small_pic1.setScaledContents(True)
        self.small_pic1.setObjectName("small_pic1")
        self.horizontalLayout_10.addWidget(self.small_pic1)
        self.verticalLayout_6.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.list_container)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_19 = QtWidgets.QFrame(self.frame_14)
        self.frame_19.setStyleSheet(
            "border-right: 4px solid red; border-radius: 0px")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.name2 = QtWidgets.QLabel(self.frame_19)
        self.name2.setStyleSheet("font: bold 12pt \"Calibri\";\n"
                                 "border-right:0px")
        self.name2.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.name2.setIndent(10)
        self.name2.setObjectName("name2")
        self.verticalLayout_8.addWidget(self.name2)
        self.id2 = QtWidgets.QLabel(self.frame_19)
        self.id2.setStyleSheet("font: 10pt \"Calibri\";\n"
                               "border-right: 0px")
        self.id2.setAlignment(QtCore.Qt.AlignRight |
                              QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.id2.setIndent(10)
        self.id2.setObjectName("id2")
        self.verticalLayout_8.addWidget(self.id2)
        self.horizontalLayout_11.addWidget(self.frame_19)
        self.small_pic2 = QtWidgets.QLabel(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.small_pic2.sizePolicy().hasHeightForWidth())
        self.small_pic2.setSizePolicy(sizePolicy)
        self.small_pic2.setMinimumSize(QtCore.QSize(85, 85))
        self.small_pic2.setMaximumSize(QtCore.QSize(85, 81))
        self.small_pic2.setText("")
        self.small_pic2.setPixmap(QtGui.QPixmap(
            ":/images/images/default-pic.png"))
        self.small_pic2.setScaledContents(True)
        self.small_pic2.setObjectName("small_pic2")
        self.horizontalLayout_11.addWidget(self.small_pic2)
        self.verticalLayout_6.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.list_container)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_21 = QtWidgets.QFrame(self.frame_15)
        self.frame_21.setStyleSheet(
            "border-right: 4px solid red; border-radius: 0px")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.name3 = QtWidgets.QLabel(self.frame_21)
        self.name3.setStyleSheet("font: bold 12pt \"Calibri\";\n"
                                 "border-right:0px")
        self.name3.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.name3.setIndent(10)
        self.name3.setObjectName("name3")
        self.verticalLayout_9.addWidget(self.name3)
        self.id3 = QtWidgets.QLabel(self.frame_21)
        self.id3.setStyleSheet("font:10pt \"Calibri\";\n"
                               "border-right: 0px")
        self.id3.setAlignment(QtCore.Qt.AlignRight |
                              QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.id3.setIndent(10)
        self.id3.setObjectName("id3")
        self.verticalLayout_9.addWidget(self.id3)
        self.horizontalLayout_12.addWidget(self.frame_21)
        self.small_pic3 = QtWidgets.QLabel(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.small_pic3.sizePolicy().hasHeightForWidth())
        self.small_pic3.setSizePolicy(sizePolicy)
        self.small_pic3.setMinimumSize(QtCore.QSize(85, 85))
        self.small_pic3.setMaximumSize(QtCore.QSize(85, 85))
        self.small_pic3.setText("")
        self.small_pic3.setPixmap(QtGui.QPixmap(
            ":/images/images/default-pic.png"))
        self.small_pic3.setScaledContents(True)
        self.small_pic3.setObjectName("small_pic3")
        self.horizontalLayout_12.addWidget(self.small_pic3)
        self.verticalLayout_6.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.list_container)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_22 = QtWidgets.QFrame(self.frame_16)
        self.frame_22.setStyleSheet(
            "border-right: 4px solid red; border-radius: 0px")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.name4 = QtWidgets.QLabel(self.frame_22)
        self.name4.setStyleSheet("font: bold 12pt \"Calibri\";\n"
                                 "border-right:0px")
        self.name4.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.name4.setIndent(10)
        self.name4.setObjectName("name4")
        self.verticalLayout_10.addWidget(self.name4)
        self.id4 = QtWidgets.QLabel(self.frame_22)
        self.id4.setStyleSheet("font:10pt \"Calibri\";\n"
                               "border-right: 0px")
        self.id4.setAlignment(QtCore.Qt.AlignRight |
                              QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.id4.setIndent(10)
        self.id4.setObjectName("id4")
        self.verticalLayout_10.addWidget(self.id4)
        self.horizontalLayout_13.addWidget(self.frame_22)
        self.small_pic4 = QtWidgets.QLabel(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.small_pic4.sizePolicy().hasHeightForWidth())
        self.small_pic4.setSizePolicy(sizePolicy)
        self.small_pic4.setMinimumSize(QtCore.QSize(85, 85))
        self.small_pic4.setMaximumSize(QtCore.QSize(85, 85))
        self.small_pic4.setText("")
        self.small_pic4.setPixmap(QtGui.QPixmap(
            ":/images/images/default-pic.png"))
        self.small_pic4.setScaledContents(True)
        self.small_pic4.setObjectName("small_pic4")
        self.horizontalLayout_13.addWidget(self.small_pic4)
        self.verticalLayout_6.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.list_container)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_23 = QtWidgets.QFrame(self.frame_17)
        self.frame_23.setStyleSheet(
            "border-right: 4px solid red; border-radius: 0px")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.name5 = QtWidgets.QLabel(self.frame_23)
        self.name5.setStyleSheet("font: bold 12pt \"Calibri\";\n"
                                 "border-right:0px")
        self.name5.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.name5.setIndent(10)
        self.name5.setObjectName("name5")
        self.verticalLayout_11.addWidget(self.name5)
        self.id5 = QtWidgets.QLabel(self.frame_23)
        self.id5.setStyleSheet("font: 10pt \"Calibri\";\n"
                               "border-right: 0px")
        self.id5.setAlignment(QtCore.Qt.AlignRight |
                              QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.id5.setIndent(10)
        self.id5.setObjectName("id5")
        self.verticalLayout_11.addWidget(self.id5)
        self.horizontalLayout_14.addWidget(self.frame_23)
        self.small_pic5 = QtWidgets.QLabel(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.small_pic5.sizePolicy().hasHeightForWidth())
        self.small_pic5.setSizePolicy(sizePolicy)
        self.small_pic5.setMinimumSize(QtCore.QSize(85, 85))
        self.small_pic5.setMaximumSize(QtCore.QSize(85, 85))
        self.small_pic5.setText("")
        self.small_pic5.setPixmap(QtGui.QPixmap(
            ":/images/images/default-pic.png"))
        self.small_pic5.setScaledContents(True)
        self.small_pic5.setObjectName("small_pic5")
        self.horizontalLayout_14.addWidget(self.small_pic5)
        self.verticalLayout_6.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.list_container)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_15.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.prev_page_button = QtWidgets.QPushButton(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.prev_page_button.sizePolicy().hasHeightForWidth())
        self.prev_page_button.setSizePolicy(sizePolicy)
        self.prev_page_button.setMinimumSize(QtCore.QSize(40, 40))
        self.prev_page_button.setStyleSheet("border-top-left-radius:10px;\n"
                                            "border-bottom-left-radius:10px;\n"
                                            "background-color: rgb(255, 170, 0)")
        self.prev_page_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            ":/icons/icons/arrow-narrow-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prev_page_button.setIcon(icon1)
        self.prev_page_button.setObjectName("prev_page_button")
        self.horizontalLayout_15.addWidget(self.prev_page_button)
        self.current_page = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.current_page.setFont(font)
        self.current_page.setStyleSheet("font: 10pt \"Calibri\"")
        self.current_page.setAlignment(QtCore.Qt.AlignCenter)
        self.current_page.setObjectName("current_page")
        self.horizontalLayout_15.addWidget(self.current_page)
        self.next_page_button = QtWidgets.QPushButton(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.next_page_button.sizePolicy().hasHeightForWidth())
        self.next_page_button.setSizePolicy(sizePolicy)
        self.next_page_button.setMinimumSize(QtCore.QSize(40, 40))
        self.next_page_button.setStyleSheet("border-top-right-radius: 10px;\n"
                                            "border-bottom-right-radius:10px;\n"
                                            "background-color:rgb(255, 170, 0)")
        self.next_page_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(
            ":/icons/icons/arrow-narrow-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_page_button.setIcon(icon2)
        self.next_page_button.setIconSize(QtCore.QSize(20, 20))
        self.next_page_button.setObjectName("next_page_button")
        self.horizontalLayout_15.addWidget(self.next_page_button)
        self.verticalLayout_6.addWidget(self.frame_18)
        self.verticalLayout_2.addWidget(self.list_container)
        self.horizontalLayout.addWidget(self.right_container)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # connect signals & slots
        self.next_page_button.clicked.connect(self.next_page)
        self.prev_page_button.clicked.connect(self.prev_page)
        self.search_button.clicked.connect(self.search)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Client"))
        self.search_input_field.setPlaceholderText(
            _translate("MainWindow", "Search by id"))
        self.profile_pic_label.setText(
            _translate("MainWindow", "Profile Picture"))
        self.info_label.setText(_translate("MainWindow", "Information"))
        self.id_container.setText(_translate("MainWindow", "id"))
        self.name_container.setText(_translate("MainWindow", "name"))
        self.phone_container.setText(_translate("MainWindow", "phone"))
        self.email_container.setText(_translate("MainWindow", "email"))
        self.name1.setText(_translate("MainWindow", "Name_1"))
        self.id1.setText(_translate("MainWindow", "id_1"))
        self.name2.setText(_translate("MainWindow", "Name_2"))
        self.id2.setText(_translate("MainWindow", "id_1"))
        self.name3.setText(_translate("MainWindow", "Name_3"))
        self.id3.setText(_translate("MainWindow", "id_3"))
        self.name4.setText(_translate("MainWindow", "Name_4"))
        self.id4.setText(_translate("MainWindow", "id_4"))
        self.name5.setText(_translate("MainWindow", "Name_5"))
        self.id5.setText(_translate("MainWindow", "id_5"))
        self.current_page.setText(_translate("MainWindow", "page"))

    # Some other functions

    def set_label_as_image(self, path: str, image_container: QtWidgets.QLabel):
        if os.path.isfile(path):
            image_container.setPixmap(QtGui.QPixmap(path))
        else:
            image_container.setPixmap(QtGui.QPixmap(
                ":/images/images/default-pic.png"))

        return image_container

    def set_label_as_text(self, text: str, text_container: QtWidgets.QLabel):
        if text == "null":
            text = ""
        _translate = QtCore.QCoreApplication.translate
        text_container.setText(_translate("MainWindow", text))

        return text_container

    def set_small_info1(self, user: Client):
        if user.is_valid():
            self.set_label_as_text(user.id, self.id1)
            self.set_label_as_text(user.fullname, self.name1)
            self.set_label_as_image(
                user.get_dir_small_avatar(), self.small_pic1)
        else:
            self.set_label_as_text("", self.id1)
            self.set_label_as_text("", self.name1)
            self.set_label_as_image("", self.small_pic1)

    def set_small_info2(self, user: Client):
        if user.is_valid():
            self.set_label_as_text(user.id, self.id2)
            self.set_label_as_text(user.fullname, self.name2)
            self.set_label_as_image(
                user.get_dir_small_avatar(), self.small_pic2)
        else:
            self.set_label_as_text("", self.id2)
            self.set_label_as_text("", self.name2)
            self.set_label_as_image("", self.small_pic2)

    def set_small_info3(self, user: Client):
        if user.is_valid():
            self.set_label_as_text(user.id, self.id3)
            self.set_label_as_text(user.fullname, self.name3)
            self.set_label_as_image(
                user.get_dir_small_avatar(), self.small_pic3)
        else:
            self.set_label_as_text("", self.id3)
            self.set_label_as_text("", self.name3)
            self.set_label_as_image("", self.small_pic3)

    def set_small_info4(self, user: Client):
        if user.is_valid():
            self.set_label_as_text(user.id, self.id4)
            self.set_label_as_text(user.fullname, self.name4)
            self.set_label_as_image(
                user.get_dir_small_avatar(), self.small_pic4)
        else:
            self.set_label_as_text("", self.id4)
            self.set_label_as_text("", self.name4)
            self.set_label_as_image("", self.small_pic4)

    def set_small_info5(self, user: Client):
        if user.is_valid():
            self.set_label_as_text(user.id, self.id5)
            self.set_label_as_text(user.fullname, self.name5)
            self.set_label_as_image(
                user.get_dir_small_avatar(), self.small_pic5)
        else:
            self.set_label_as_text("", self.id5)
            self.set_label_as_text("", self.name5)
            self.set_label_as_image("", self.small_pic5)

    def setup_initial_info(self):
        self.set_small_info1(contacts_list.load_client(1, 0))
        self.set_small_info2(contacts_list.load_client(1, 1))
        self.set_small_info3(contacts_list.load_client(1, 2))
        self.set_small_info4(contacts_list.load_client(1, 3))
        self.set_small_info5(contacts_list.load_client(1, 4))
        self.set_label_as_text(str(contacts_list.cur_page), self.current_page)

    def next_page(self):
        page_list = contacts_list.next_page()
        self.set_small_info1(page_list[0])
        self.set_small_info2(page_list[1])
        self.set_small_info3(page_list[2])
        self.set_small_info4(page_list[3])
        self.set_small_info5(page_list[4])
        self.set_label_as_text(str(contacts_list.cur_page), self.current_page)

    def prev_page(self):
        page_list = contacts_list.prev_page()
        self.set_small_info1(page_list[0])
        self.set_small_info2(page_list[1])
        self.set_small_info3(page_list[2])
        self.set_small_info4(page_list[3])
        self.set_small_info5(page_list[4])
        self.set_label_as_text(str(contacts_list.cur_page), self.current_page)

    def search(self):
        query = self.search_input_field.text()
        res = contacts_list.find_by_id(query)
        if res.is_valid():
            res = get_full_info(query)
            get_big_ava(query)
        self.set_label_as_image(res.get_dir_big_avatar(),
                                self.big_pic_container)
        self.set_label_as_text(res.id, self.id_container)
        self.set_label_as_text(res.fullname, self.name_container)
        self.set_label_as_text(res.contact, self.phone_container)
        self.set_label_as_text(res.email, self.email_container)


def delete_data():
    for filename in os.listdir(BIG_PIC_FOLDER):
        os.remove(os.path.join(BIG_PIC_FOLDER, filename))
    for filename in os.listdir(SMALL_PIC_FOLDER):
        os.remove(os.path.join(SMALL_PIC_FOLDER, filename))


# Receive a list from server


def recvList(conn):
    list = []
    item = conn.recv(1024).decode(FORMAT)
    while(item != "end"):
        list.append(item)
        conn.sendall(item.encode(FORMAT))
        item = conn.recv(1024).decode(FORMAT)
    return list

# Receive a file from server


def recvFile(conn):
    fileInfo = conn.recv(BUFFER_SIZE).decode(FORMAT)
    conn.sendall("ReadyToReceiveFile".encode(FORMAT))
    fileName, fileSize = fileInfo.split(SEPARATOR)
    #fileName = ".\\data\\" + os.path.basename(fileName)
    fileSize = int(fileSize)
    bytes_count = 0
    bytes_write_count = 0
    fileOut = open(fileName, "wb")
    condition = 1
    while (condition == 1):
        # Receive 1024 bytes from the socket
        bytes_read = conn.recv(BUFFER_SIZE)
        bytes_count += len(bytes_read)

        if bytes_count < fileSize:
            fileOut.write(bytes_read)
            bytes_write_count += len(bytes_read)
            # print('writing', len(bytes_read))
        elif bytes_count == fileSize:
            # print('equal')
            fileOut.write(bytes_read)
            bytes_write_count += len(bytes_read)
            bytes_read = conn.recv(BUFFER_SIZE)  # end message
            bytes_count += len(bytes_read)
            break
        else:
            diff = bytes_count - fileSize
            # print('diff:', diff)
            if diff == END_MESSAGE_SIZE:
                fileOut.write(bytes_read[:-END_MESSAGE_SIZE])
                bytes_write_count += len(bytes_read[:-END_MESSAGE_SIZE])
            else:
                fileOut.write(bytes_read[:-diff])
                bytes_write_count += len(bytes_read[:-diff])
                bytes_read = conn.recv(BUFFER_SIZE)
                bytes_count += len(bytes_read)
            break

        # Write to the file the bytes we just received
        # fileOut.write(bytes_read)
    print("File is transfered: ", fileSize, "recv:",
          bytes_count, "write:", bytes_write_count)
    fileOut.close()
    return fileName


def get_initial_list():
    msg = "list"
    client.sendall(msg.encode(FORMAT))
    num = int(client.recv(BUFFER_SIZE).decode(FORMAT))
    client.send(msg.encode(FORMAT))
    for i in range(num):
        memInfo = recvList(client)
        mem = Client(memInfo)
        members.append(mem)
        client.send(msg.encode(FORMAT))
    contacts_list = ClientList(members)


def get_small_ava_list():
    msg = "small ava"
    client.sendall(msg.encode(FORMAT))
    num = int(client.recv(BUFFER_SIZE).decode(FORMAT))
    client.send(msg.encode(FORMAT))
    for i in range(num):
        members[i].smallAvaPath = recvFile(client)
        client.send(msg.encode(FORMAT))


def get_big_ava(id):
    msg = "big ava"
    client.sendall(msg.encode(FORMAT))
    client.recv(BUFFER_SIZE)
    client.send(str(id).encode(FORMAT))
    members[int(id)].bigAvaPath = recvFile(client)
    return members[int(id)].bigAvaPath


def get_full_info(id):
    msg = "info"
    client.sendall(msg.encode(FORMAT))
    client.recv(BUFFER_SIZE)
    client.send(str(id).encode(FORMAT))
    addInfo = recvList(client)
    for i in range(len(contacts_list.client_list)):
        if contacts_list.client_list[i].id == str(id):
            contacts_list.client_list[i].contact = addInfo[0]
            contacts_list.client_list[i].email = addInfo[1]
            return contacts_list.client_list[i]

    return Client(None)
    # members[id].contact = addInfo[0]
    # members[id].email = addInfo[1]


def close_connection():
    msg = "x"
    client.sendall(msg.encode(FORMAT))


def close_all_connection():
    print('closing all connection')


app = QtWidgets.QApplication(sys.argv)

if __name__ == '__main__':
    # Initialize socket & members list
    global client
    client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    print("CLIENT SIDE")
    global members
    members = []
    global contacts_list
    contacts_list = ClientList(members)

    # Connect to server
    try:

        client.connect((HOST, SERVER_PORT))
        print("Client address: ", client.getsockname())

        # getting initial information
        get_initial_list()
        get_small_ava_list()

        # gui starts
        ui_object = Ui_MainWindow()
        window_object = QtWidgets.QMainWindow()
        ui_object.setupUi(window_object)
        ui_object.setup_initial_info()
        window_object.show()
        print('app started')
        app.exec_()
        print('app ended')
        close_connection()
        client.close()
        print('client closed')

    except Exception:
        print("Error occured.")
        # traceback.print_exception()

    delete_data()
    print('cached data deleted')
